package com.project.myscale.ui.theme

import androidx.compose.ui.graphics.Color

// Forest Theme (Light, Green)
val ForestPrimary = Color(0xFF4CAF50)
val ForestPrimaryContainer = Color(0xFFC8E6C9)
val ForestSecondary = Color(0xFF81C784)
val ForestSecondaryContainer = Color(0xFFE8F5E9)
val ForestTertiary = Color(0xFFFF8A65)
val ForestBackground = Color(0xFFFAFFF5)
val ForestSurface = Color(0xFFFFFFFF)
val ForestSurfaceVariant = Color(0xFFF1F8E9)
val ForestOnBackground = Color(0xFF1B2E1B)
val ForestOnSurface = Color(0xFF1B2E1B)
val ForestOnPrimary = Color(0xFFFFFFFF)
val ForestOnPrimaryContainer = Color(0xFF1B5E20)
val ForestOnSecondary = Color(0xFFFFFFFF)
val ForestOnSecondaryContainer = Color(0xFF1B5E20)
val ForestOnTertiary = Color(0xFFFFFFFF)
val ForestOutline = Color(0xFF8BC34A)
val ForestOutlineVariant = Color(0xFFC5E1A5)
val ForestSurfaceTint = Color(0xFF4CAF50)
val ForestError = Color(0xFFBA1A1A)
val ForestOnError = Color(0xFFFFFFFF)
val ForestErrorContainer = Color(0xFFFFDAD6)
val ForestOnErrorContainer = Color(0xFF410002)

// Midnight Theme (Dark)
val MidnightPrimary = Color(0xFFBB86FC)
val MidnightPrimaryContainer = Color(0xFF3700B3)
val MidnightSecondary = Color(0xFF03DAC6)
val MidnightSecondaryContainer = Color(0xFF004D40)
val MidnightTertiary = Color(0xFFCF6679)
val MidnightBackground = Color(0xFF121212)
val MidnightSurface = Color(0xFF1E1E1E)
val MidnightSurfaceVariant = Color(0xFF2D2D2D)
val MidnightOnBackground = Color(0xFFE1E1E1)
val MidnightOnSurface = Color(0xFFFFFFFF)
val MidnightOnPrimary = Color(0xFF1E1E1E)
val MidnightOnPrimaryContainer = Color(0xFFE1BEE7)
val MidnightOnSecondary = Color(0xFF1E1E1E)
val MidnightOnSecondaryContainer = Color(0xFFA7FFEB)
val MidnightOnTertiary = Color(0xFF1E1E1E)
val MidnightOutline = Color(0xFF938F99)
val MidnightOutlineVariant = Color(0xFF49454F)
val MidnightSurfaceTint = Color(0xFFBB86FC)
val MidnightError = Color(0xFFCF6679)
val MidnightOnError = Color(0xFF1E1E1E)
val MidnightErrorContainer = Color(0xFF93000A)
val MidnightOnErrorContainer = Color(0xFFFFDAD6)

// Sunset Theme (Light, Warm)
val SunsetPrimary = Color(0xFFFF7043)
val SunsetPrimaryContainer = Color(0xFFFFCCBC)
val SunsetSecondary = Color(0xFFFFB74D)
val SunsetSecondaryContainer = Color(0xFFFFF3E0)
val SunsetTertiary = Color(0xFF8D6E63)
val SunsetBackground = Color(0xFFFFF8F0)
val SunsetSurface = Color(0xFFFFFFFF)
val SunsetSurfaceVariant = Color(0xFFFBE9E7)
val SunsetOnBackground = Color(0xFF3E2723)
val SunsetOnSurface = Color(0xFF3E2723)
val SunsetOnPrimary = Color(0xFFFFFFFF)
val SunsetOnPrimaryContainer = Color(0xFFBF360C)
val SunsetOnSecondary = Color(0xFF3E2723)
val SunsetOnSecondaryContainer = Color(0xFFE65100)
val SunsetOnTertiary = Color(0xFFFFFFFF)
val SunsetOutline = Color(0xFFFFAB91)
val SunsetOutlineVariant = Color(0xFFFFCCBC)
val SunsetSurfaceTint = Color(0xFFFF7043)
val SunsetError = Color(0xFFBA1A1A)
val SunsetOnError = Color(0xFFFFFFFF)
val SunsetErrorContainer = Color(0xFFFFDAD6)
val SunsetOnErrorContainer = Color(0xFF410002)

// Common colors
val TrendPositive = Color(0xFF4CAF50)
val TrendNegative = Color(0xFFE53935)
val TrendNeutral = Color(0xFF9E9E9E)
